-- Add remaining VIOS allergens from PDFs 10-12 (R-Z)
INSERT INTO public.vios_allergies (vios_code, name, is_active)
VALUES
  -- PDF 10: R-T allergens
  (533, 'Ribociclib', true),
  (750, 'Rice Derivatives', true),
  (660, 'Rifamycin', true),
  (35, 'Rifamycins', true),
  (707, 'Risankizumab', true),
  (1025, 'Ritlecitinib', true),
  (154, 'Rivastigmine', true),
  (462, 'Rotavirus A type Live Antigens (Human)', true),
  (470, 'Rubella', true),
  (998, 'Rye', true),
  (534, 'Safinamide', true),
  (456, 'Salicylates (non-aspirin)', true),
  (87, 'salicylates', true),
  (1065, 'Sarsaparilla', true),
  (968, 'SARS-CoV-2 Recombinant Spike Protein', true),
  (160, 'Scopolamine', true),
  (1005, 'Sea Buckthorn', true),
  (1190, 'Sea Sponge (Porifera) Derivatives', true),
  (985, 'Seaweed and Kelp', true),
  (454, 'Secretin', true),
  (1070, 'Seladelpar', true),
  (1164, 'Selective Nav1.8 sodium channel blockers', true),
  (813, 'Selective norepinephrine reuptake inhibitors', true),
  (975, 'Selective prostaglandin E2 (EP2) receptor agonists', true),
  (732, 'Selective Serotonin 1F Receptor Agonists', true),
  (153, 'Selective serotonin reuptake inhibitors', true),
  (1080, 'Selective transthyretin (TTR) stabilizers', true),
  (352, 'Selenium', true),
  (769, 'Selpercatinib', true),
  (943, 'Selumetinib', true),
  (1020, 'Semifluorinated Alkanes', true),
  (822, 'Semisynthetic Ergot Derivatives', true),
  (868, 'Senna', true),
  (869, 'Sennosides', true),
  (111, 'Serotonin receptor agonists', true),
  (148, 'Serotonin-Receptor Antagonists', true),
  (875, 'Serratiopeptidase', true),
  (793, 'Sesame', true),
  (1156, 'Sevelamer', true),
  (467, 'SGLT2 inhibitors', true),
  (496, 'Shark Cartilage', true),
  (40, 'Sheep (Ovine) Derivatives', true),
  (791, 'Shellfish Derivatives', true),
  (891, 'Sibutramine', true),
  (858, 'Silica', true),
  (857, 'Silicate', true),
  (681, 'Silicone', true),
  (565, 'Silicon', true),
  (839, 'Silk', true),
  (744, 'Silver and Silver Derivatives', true),
  (296, 'Simeprevir', true),
  (417, 'Sincalide', true),
  (702, 'Siponimod', true),
  (900, 'Sirolimus', true),
  (250, 'Snake (Serpentes) Derivatives', true),
  (616, 'Sodium Zirconium', true),
  (1059, 'Sofpironium', true),
  (1155, 'Solifenacin', true),
  (704, 'Solriamfetol', true),
  (802, 'Soluble guanylate cyclase stimulators', true),
  (881, 'Somatropin', true),
  (961, 'Sorbitol', true),
  (43, 'Soy', true),
  (353, 'Spectinomycin', true),
  (701, 'Sphingosine 1-phosphate receptor modulators', true),
  (1038, 'Squash', true),
  (1015, 'Stevia and Derivatives', true),
  (564, 'St. Johns Wort', true),
  (999, 'Strawberry Derivatives', true),
  (469, 'Streptococcus Pneumoniae Antigens', true),
  (34, 'Streptogramins', true),
  (588, 'Strontium', true),
  (115, 'Succinimides', true),
  (852, 'Sucrose Fatty Acid Esters', true),
  (1151, 'Sugammadex', true),
  (37, 'Sulfa/Sulfonamides', true),
  (88, 'Sulfites', true),
  (696, 'Sulfonamides (topical)', true),
  (840, 'Sulfone', true),
  (69, 'Sulfonylureas', true),
  (1187, 'Sunflower', true),
  (1150, 'Sunitinib', true),
  (830, 'Sunscreens', true),
  (143, 'Sympathomimetics', true),
  (781, 'Tafasitamab', true),
  (637, 'Tafenoquine', true),
  (649, 'Talazoparib', true),
  (1208, 'Taletrectinib', true),
  (972, 'Taliglucerase alfa', true),
  (1043, 'Tamarind', true),
  (354, 'Tamsulosin', true),
  (1095, 'Tapioca', true),
  (86, 'Tartrazine dye', true),
  (1032, 'Taurine and Derivatives', true),
  (50, 'Taxanes', true),
  
  -- PDF 11: T-V allergens
  (756, 'Tazemetostat', true),
  (925, 'Technetium-based Radiopharmaceuticals', true),
  (1201, 'Telisotuzumab', true),
  (531, 'Telotristat', true),
  (727, 'Tenapor', true),
  (490, 'Tenofovir', true),
  (591, 'Terbinafine', true),
  (1147, 'Terbutaline', true),
  (989, 'Tesamorelin', true),
  (287, 'Tetanus', true),
  (790, 'Tetanus Toxoid Conjugate', true),
  (538, 'Tetrabenazine Analogs', true),
  (152, 'Tetracyclic compounds', true),
  (76, 'Tetracyclines', true),
  (1146, 'Tetrahydrozoline', true),
  (1071, 'Tetraxetan', true),
  (219, 'Thalidomide Analogues', true),
  (1101, 'Thallium Compounds', true),
  (30, 'Thiazide diuretics', true),
  (216, 'Thiazolidinediones', true),
  (293, 'Thienopyridines', true),
  (592, 'Thioamides', true),
  (205, 'Thiol Derivatives', true),
  (1078, 'Thiopenems', true),
  (457, 'Thiosulfates', true),
  (419, 'Thiotepa', true),
  (261, 'Thiothixene', true),
  (842, 'Thiuram Derivatives', true),
  (251, 'Thrombin (Recombinant)', true),
  (609, 'Thrombolytic Agents', true),
  (615, 'Thrombopoetin receptor agonists', true),
  (1044, 'Thyroid hormone receptor beta agonist', true),
  (447, 'Thyroid Hormones', true),
  (458, 'Thyrotropin', true),
  (944, 'Timolol', true),
  (1173, 'Tin and Tin Derivatives', true),
  (290, 'Tiotropium', true),
  (246, 'Tipranavir', true),
  (1145, 'Tirofiban', true),
  (566, 'Titanium', true),
  (1144, 'Tivozanib', true),
  (677, 'Tobacco', true),
  (137, 'Tocainide', true),
  (356, 'Tolazoline', true),
  (420, 'Tolnaftate', true),
  (657, 'Tolterodine', true),
  (625, 'Tomato', true),
  (787, 'Topical Androgen Receptor Inhibitors', true),
  (1136, 'Toremifene', true),
  (772, 'Trabectedin analogues', true),
  (72, 'Tramadol', true),
  (748, 'Trastuzumab', true),
  (421, 'Trazodone', true),
  (294, 'Tree Nuts', true),
  (422, 'Triacetin', true),
  (151, 'Tricyclic Compounds', true),
  (357, 'Trientine', true),
  (62, 'Triethanolamine derivatives', true),
  (423, 'Triethanolamine', true),
  (424, 'Trifluridine', true),
  (358, 'Trimethobenzamide', true),
  (359, 'Trimethoprim', true),
  (856, 'Trimonium', true),
  (843, 'Triple Dye', true),
  (826, 'Triterpenoid antifungals', true),
  (1017, 'Trofinetide', true),
  (1135, 'Tromethamine', true),
  (663, 'Tropomyosin Receptor Kinase (TRK) inhibitors', true),
  (945, 'Trospium', true),
  (786, 'Tryptophan', true),
  (455, 'Tuberculin', true),
  (524, 'Turmeric and other Curcuma species', true),
  (593, 'Tumor Necrosis Factor Modifiers', true),
  (598, 'Typhoid Vaccine, Live Ty21a', true),
  (973, 'Tyrosine kinase 2 (TYK2) inhibitors', true),
  (666, 'Tyrosine kinase 3 (FLT3) inhibitors', true),
  (1134, 'Ulipristal', true),
  (811, 'Umbralisib', true),
  (710, 'Umeclidinium', true),
  (485, 'Undaria Pinnatifida', true),
  (425, 'Undecylenates', true),
  (464, 'Urea', true),
  (426, 'Urokinase', true),
  (1170, 'Urticaceae', true),
  (878, 'Valerian', true),
  (1051, 'Valoctocogene Roxaparvovec', true),
  (448, 'Valproic Acid', true),
  (952, 'Vanadium', true),
  (449, 'Vancomycin', true),
  (1133, 'Varenicline', true),
  (172, 'Vasopressin analogs', true),
  (1116, 'Vasopressin Receptor Antagonists', true),
  (1122, 'Vegetable Derivatives (unspecified)', true),
  (544, 'Venlafaxine', true),
  (969, 'Verapamil', true),
  (427, 'Vidarabine', true),
  (1172, 'Vilanterol', true),
  (1089, 'Vilazodone', true),
  (814, 'Viloxazine', true),
  (1166, 'Vimseltinib', true),
  
  -- PDF 12: V-Z allergens
  (29, 'Vinca alkaloids', true),
  (125, 'Vitamin A and derivatives', true),
  (355, 'Vitamin B1', true),
  (603, 'Vitamin B', true),
  (126, 'Vitamin D and derivatives', true),
  (841, 'Vitamin E', true),
  (493, 'Vitis Vinifera', true),
  (931, 'Voclosporin', true),
  (950, 'Vonoprazan', true),
  (1091, 'Vorapaxar', true),
  (964, 'Vutrisiran', true),
  (1115, 'Water (plain, unpreserved)', true),
  (289, 'Wheat', true),
  (919, 'Whey proteins', true),
  (849, 'White Dyes', true),
  (844, 'Wool alcohols', true),
  (1076, 'Xanomeline', true),
  (1026, 'Xanthan gum and derivatives', true),
  (45, 'Xanthine Derivatives', true),
  (1004, 'Xenon Derivatives', true),
  (758, 'Yeast-derived', true),
  (210, 'Yeasts', true),
  (553, 'Yellow Dyes', true),
  (51, 'Yohimbine', true),
  (652, 'Zaleplon', true),
  (1031, 'Zilucoplan', true),
  (511, 'Zinc', true),
  (653, 'Zolpidem', true),
  (281, 'Zonisamide', true),
  (276, 'Zoster Vaccine Live (Bovine)', true)
ON CONFLICT (vios_code) DO UPDATE SET
  name = EXCLUDED.name,
  is_active = true,
  updated_at = now();