-- Clear existing data and insert all VIOS allergens from the official PDF export
-- This comprehensive list includes ~700+ allergens with their VIOS codes

TRUNCATE TABLE public.vios_allergies RESTART IDENTITY;

INSERT INTO public.vios_allergies (vios_code, name, is_active) VALUES
-- PDF 1: A allergens
(98, '4-aminoquinolines', true),
(4, '5-Alpha reductase inhibitors', true),
(100, '8-aminoquinolines', true),
(955, 'Abiraterone', true),
(918, 'Abrocitinib', true),
(1117, 'Acacia Derivatives', true),
(986, 'Acamprosate', true),
(1102, 'Acesulfame', true),
(345, 'Acetaminophen', true),
(956, 'Acetic acid', true),
(301, 'Acetylcholine', true),
(302, 'Acetylcysteine', true),
(703, 'Aclidinium', true),
(1204, 'Acoltremon', true),
(1046, 'Activin signaling inhibitors', true),
(89, 'Acyclovir derivatives', true),
(1103, 'Adefovir', true),
(816, 'Adenovirus SARS-CoV-2 (Covid-19)', true),
(556, 'Adhesive', true),
(1019, 'Agave and Yucca Derivatives', true),
(429, 'Albumin Human', true),
(765, 'Albuterol', true),
(1124, 'Alclometasone', true),
(107, 'Alcohol', true),
(927, 'Algae and Derivatives', true),
(876, 'Alglucosidase alfa', true),
(957, 'Aliskiren', true),
(650, 'ALK inhibitors', true),
(833, 'Alkylamine Antihistamines', true),
(1160, 'Alkyl Sulfonate Alkylating Agents', true),
(887, 'Allogeneic Processed Thymus Tissue', true),
(303, 'Allopurinol', true),
(260, 'Almotriptan', true),
(545, 'Aloe', true),
(132, 'Alpha-glucosidase Inhibitors', true),
(108, 'Alpha interferons', true),
(673, 'Alpha-pinene', true),
(193, 'Aluminum', true),
(430, 'Amantadine', true),
(123, 'Amantidine agents', true),
(623, 'Amaranthaceae', true),
(431, 'Ambenonium', true),
(6, 'Amide local anesthetics', true),
(1193, 'Amikacin', true),
(432, 'Amiloride', true),
(910, 'Aminoglutethimide', true),
(8, 'Aminoglycosides', true),
(171, 'Aminoketone phenylethylamine derivatives', true),
(433, 'Aminophylline', true),
(668, 'Aminopyridines', true),
(434, 'Aminosalicylic acid', true),
(435, 'Amiodarone', true),
(716, 'Amlodipine', true),
(796, 'Ammonia', true),
(797, 'Ammonium', true),
(459, 'Amphetamines', true),
(218, 'Amphotericin', true),
(121, 'Amprenavir', true),
(981, 'Anagrelide', true),
(110, 'Androgens', true),
(1205, 'Andrographis', true),
(10, 'Angiotensin-converting enzyme inhibitors', true),
(1012, 'Angiotensin II and Endothelin receptor antagonist', true),
(9, 'Angiotensin II receptor antagonists', true),
(11, 'Anthracyclines', true),
(436, 'Anthralin', true),
(895, 'Antibody-drug conjugates containing vedotin', true),
(600, 'Anticonvulsants', true),
(1006, 'Antiestrogens', true),
(504, 'Antimony Compounds', true),
(785, 'Antisense Oligonucleotides for Duchenne', true),
(812, 'Apiaceae', true),
(982, 'Apomorphine', true),
(665, 'Apple', true),
(437, 'Apraclonidine', true),
(576, 'Aprepitant', true),
(966, 'Apricot', true),
(438, 'Aprotinin', true),
(484, 'Arbutin', true),
(939, 'Ardeparin', true),
(807, 'Arfomoterol', true),
(360, 'Arginine', true),
(1074, 'Arimoclomol', true),
(847, 'Aripiprazole', true),
(1184, 'Artemisinin and Derivatives Antimalarial Agents', true),
(896, 'Asciminib', true),
(439, 'Ascorbic acid (Vitamin C)', true),
(959, 'Asenapine', true),
(112, 'Asparaginase and related compounds', true),
(988, 'Asparaginase (Erwinia chrysanthemi)', true),
(1090, 'Asparagus', true),
(505, 'Asteraceae (Compositae)', true),
(1035, 'Astragalus', true),
(679, 'Atropine', true),
(529, 'Autologous Cultured Chondrocytes', true),

-- PDF 2: A-B allergens
(617, 'Avatrombopag', true),
(621, 'Avermectins', true),
(506, 'Avocado Oil', true),
(1197, 'Avutometinib', true),
(304, 'Azathioprine', true),
(1125, 'Azelastine', true),
(92, 'Azole antifungals', true),
(1063, 'Bacillus', true),
(243, 'Bacitracin', true),
(363, 'Baclofen', true),
(946, 'Bacteriostatic Water', true),
(794, 'Baloxavir', true),
(634, 'Balsam of Peru', true),
(792, 'Bamlanivimab', true),
(491, 'Banana', true),
(13, 'Barbiturates', true),
(579, 'Barium', true),
(997, 'Barley', true),
(574, 'Beans', true),
(114, 'Bee allergens', true),
(113, 'Bee (Apis Mellifera) Venom', true),
(39, 'Beef and Cow (Bovine) Derivatives', true),
(851, 'Beet Derivatives', true),
(936, 'Behenic Acid and Derivatives', true),
(83, 'Belladonna alkaloids', true),
(680, 'Belladonna', true),
(1126, 'Belumosudil', true),
(1127, 'Benoxinate', true),
(450, 'Benzalkonium Chloride', true),
(575, 'Benzhydrocodone', true),
(162, 'Benzimidazole anthelmintics', true),
(221, 'Benzisoxazole Derivatives', true),
(70, 'Benzodiazepine derivatives', true),
(248, 'Benzoic Acid', true),
(835, 'Benzothiazepine Calcium-channel blockers', true),
(247, 'Benzoyl Peroxide', true),
(305, 'Benztropine', true),
(271, 'Benzyl alcohol', true),
(1128, 'Bepotastine', true),
(1110, 'Bepridil', true),
(1042, 'Berberine and related compounds', true),
(1041, 'Berdazimer', true),
(800, 'Beta-3 adrenergic agonists', true),
(1216, 'Beta-agonists', true),
(140, 'Beta Blockers (all)', true),
(173, 'Beta-glucocerebrosidase derivatives', true),
(715, 'Betaine', true),
(133, 'Beta-lactamase inhibitors', true),
(306, 'Bethanechol', true),
(907, 'Bifidobacterium Probiotics', true),
(440, 'Biguanides', true),
(867, 'Bile Acids and Bile Salts', true),
(59, 'Bile acid sequestrants', true),
(174, 'Bioflavonoids', true),
(960, 'Biosaccharide Gum', true),
(1154, 'Biperiden', true),
(168, 'Bipyridine inotropic agents', true),
(1040, 'Birch bark derivatives', true),
(198, 'Bird (Avian) Derivatives', true),
(441, 'Bisacodyl', true),
(1210, 'Bisbiguanide disinfectants', true),
(64, 'Bismuth', true),
(93, 'Bisphosphonates', true),
(1157, 'Bitolterol', true),
(1067, 'Blackberry', true),
(1106, 'Black Cohosh', true),
(1188, 'Black mustard seed', true),
(307, 'Bleomycin', true),
(1066, 'Blueberry', true),
(546, 'Blue Dyes', true),
(209, 'Boron/Boronic Acid Derivatives', true),
(159, 'Botulinum toxins', true),
(630, 'BRAF inhibitors', true),
(932, 'Brassicaceae (Cruciferae)', true),
(713, 'Bremelanotide', true),
(1214, 'Brensocatib', true),
(1129, 'Bretylium', true),
(1130, 'Brimonidine', true),
(517, 'Broccoli Derivatives', true),
(228, 'Bromides', true),
(516, 'Brussels Sprout', true),
(563, 'Bruton tyrosine kinase (BTK) inhibitors', true),
(1096, 'Buckwheat', true),
(1028, 'Buspirone and related Analogs', true),
(308, 'Buspirone', true),
(361, 'Busulfan', true),
(1131, 'Butenafine', true),
(103, 'Butyrophenones', true),

-- PDF 2-3: C allergens
(518, 'Cabbage', true),
(643, 'Calcitonin gene-related peptide antagonist monoclonal antibodies', true),
(594, 'Calcium', true),
(547, 'Camphor and related compounds', true),
(189, 'Camptothecin analogs', true),
(850, 'Cane Sugar and Derivatives', true),
(220, 'Cannabinoids', true),
(624, 'Cannabis', true),
(508, 'Cantharidin Derivatives', true),
(362, 'Capreomycin', true),
(117, 'Capsaicin compounds', true),
(15, 'Carbacephems', true),
(442, 'Carbachol', true),
(116, 'Carbamates', true),
(163, 'Carbamazepine and derivatives', true),
(3, 'Carbapenems', true),
(1153, 'Carbetapentane', true),
(84, 'Carbidopa', true),
(73, 'Carbonic anhydrase inhibitors', true),
(1132, 'Carboxymethylcellulose', true),
(56, 'Cardiac glycosides', true),
(947, 'Cardiac myosin inhibitors', true),
(934, 'Carmine', true),
(175, 'Castor Oil', true),
(1022, 'Cat (Feline) Derivatives', true),
(683, 'CD123-directed cytotoxin', true),
(560, 'CDK 4/6 inhibitors', true),
(739, 'Cefiderocol', true),
(740, 'Ceftaroline', true),
(277, 'Celecoxib', true),
(595, 'Cellulose', true),
(499, 'Centella Asiatica (Gotu Kola)', true),
(2, 'Cephalosporins', true),
(935, 'Ceramides and Derivatives', true),
(818, 'Ceteareths', true),
(149, 'Cetirizine', true),
(1213, 'Cetuximab', true),
(892, 'Charcoal', true),
(510, 'Cherry', true),
(550, 'Chia', true),
(726, 'Chickpea', true),
(1167, 'Chikungunya virus vaccines', true),
(275, 'Chitosan', true),
(1112, 'Chlophedianol', true),
(118, 'Chloral hydrate', true),
(452, 'Chlorambucil', true),
(364, 'Chloramphenicol', true),
(309, 'Chlorhexidine', true),
(577, 'Chlorpheniramine', true),
(365, 'Chlorzoxazone', true),
(978, 'Chocolate and Cocoa Derivatives', true),
(1137, 'Choline', true),
(583, 'Cholinergic agonists', true),
(18, 'Cholinesterase inhibitors', true),
(366, 'Ciclopirox', true),
(278, 'Cidofovir', true),
(1138, 'Cilastatin', true),
(596, 'Cimetidine', true),
(1139, 'Cinacalcet', true),
(99, 'Cinchona alkaloids', true),
(1194, 'Cinnamal', true),
(632, 'Cinnamates', true),
(633, 'Cinnamon and related compounds', true),
(191, 'Citalopram and derivatives', true),
(1140, 'Citicoline', true),
(860, 'Citric Acid', true),
(1195, 'Citronella and Derivatives', true),
(671, 'Citronella', true),
(526, 'Citrus', true),
(94, 'Clavulanic acid derivatives', true),
(310, 'Clidinium', true),
(1141, 'Clobetasol', true),
(1142, 'Clocortolone', true),
(1107, 'Clomiphene', true),
(201, 'Clonidine Derivatives', true),
(298, 'Coagulation Factor IX', true),
(453, 'Coal tar', true),
(478, 'Cobalt', true),
(767, 'Cobimetinib', true),
(933, 'Cochineal Dyes', true),
(1083, 'Cockroach', true),
(980, 'Coconut and Derivatives', true),
(1206, 'Codeine', true),
(190, 'Cod liver oil and derivatives', true),
(752, 'Coffee', true),
(367, 'Colchicine', true),
(60, 'Colistin (Polymyxins)', true),
(444, 'Collagenase', true),
(57, 'Colony Stimulating Factors', true),
(886, 'Complement 5a receptor (C5aR) antagonists', true),
(1037, 'Complement Factor B inhibitor', true),
(1047, 'Complement Factor D inhibitors', true),
(188, 'COMT inhibitors', true),
(1064, 'Copper-based Radiopharmaceuticals', true),
(597, 'Copper', true),
(66, 'Corn derivatives', true),
(19, 'Corticosteroids', true),
(368, 'Cosyntropin', true),
(1108, 'Cotton and Derivatives', true),
(252, 'Coumarins', true),
(549, 'Cranberry', true),
(1143, 'Creatine', true),
(230, 'Cresol', true),
(311, 'Cromolyn', true),
(369, 'Crotamiton', true),
(1027, 'CXC receptor-4 (CXCR4) inhibitors', true),
(1169, 'Cyanobacteria', true),
(477, 'Cyanocobalmin', true),

-- PDF 4: C-D allergens
(78, 'Cyclobenzaprine', true),
(483, 'Cyclodextrins', true),
(1149, 'Cyclomethicones', true),
(1148, 'Cyclopentolate', true),
(370, 'Cycloserine', true),
(371, 'Cyclosporine', true),
(82, 'Cysteamine', true),
(902, 'Cysteine', true),
(1087, 'Cystic Fibrosis Transmembrane Conductance Regulator (CFTR) Modulators', true),
(889, 'Cytarabine', true),
(774, 'Cytidine deaminase (CDA) inhibitors', true),
(864, 'Dabigatran', true),
(204, 'Dacarbazine / Temozolomide', true),
(746, 'Daclizumab', true),
(372, 'Dactinomycin', true),
(628, 'Dairy', true),
(312, 'Dantrolene', true),
(709, 'Dapagliflozin', true),
(1100, 'Dapiprazole', true),
(916, 'Daridorexant', true),
(279, 'Darunavir', true),
(983, 'Dasabuvir', true),
(1081, 'Dates', true),
(1196, 'Defactinib', true),
(313, 'Deferoxamine', true),
(708, 'Dengue vaccine', true),
(207, 'Denileukin Diftitox', true),
(543, 'Desvenlafaxine', true),
(61, 'Dextran', true),
(971, 'Dextromethorphan', true),
(297, 'Dextrose', true),
(142, 'Diazoxide', true),
(753, 'Dibenzoxazepines', true),
(119, 'Dichloralphenazone', true),
(314, 'Dicyclomine', true),
(599, 'Dideoxynucleosides', true),
(659, 'Diethyl Sebacate', true),
(1118, 'Diethyltoluamide (DEET)', true),
(880, 'Difelikefalin', true),
(138, 'Dihydropyridine Calcium-channel Blockers', true),
(254, 'Dimethicone', true),
(736, 'Dimethyl fumarate', true),
(970, 'Dimethyl sulfoxide (DMSO)', true),
(282, 'Dipeptidyl Peptidase-4 Inhibitors', true),
(315, 'Diphenhydramine', true),
(161, 'Diphenoxylic acid derivatives', true),
(185, 'Diphenylheptane opioids', true),
(951, 'Diphtheria Toxoid and Conjugate Derivatives', true),
(374, 'Dipyridamole', true),
(735, 'Diroximel Fumarate', true),
(316, 'Disopyramide', true),
(375, 'Disulfiram', true),
(1082, 'Docosahexaenoic acid (DHA) derivatives', true),
(828, 'Docusate', true),
(640, 'Dog (Canine) Derivatives', true),
(567, 'Dolutegravir', true),
(1215, 'Donidalorsen', true),
(700, 'Dopamine and Norepinephrine Reuptake Inhibitor (DNRI)', true),
(1212, 'Dordaviprone', true),
(1072, 'Dotatate-containing compounds', true),
(1171, 'Duloxetine', true),

-- PDF 4-5: E-F allergens
(468, 'Echinacea', true),
(262, 'Echinocandins', true),
(1198, 'Echothiophate', true),
(317, 'Edetate disodium', true),
(645, 'EGFR Kinase Inhibitors', true),
(629, 'Egg and Egg Derivatives', true),
(1007, 'Elacestrant', true),
(1055, 'Elafibranor', true),
(639, 'Elagolix', true),
(1217, 'Elamipretide', true),
(500, 'Eleutherococcus senticosus (Siberian ginseng)', true),
(318, 'Encainide', true),
(1010, 'Endothelin receptor antagonists', true),
(920, 'Enoxaparin', true),
(1085, 'Ensartinib', true),
(180, 'Epipodophyllotoxins', true),
(1182, 'Equisetaceae', true),
(120, 'Ergot alkaloids', true),
(984, 'Erlotinib', true),
(176, 'Erythropoietin and related compounds', true),
(698, 'Esketamine', true),
(134, 'Ester anesthetics', true),
(572, 'Estramustine', true),
(202, 'Estrogens', true),
(654, 'Eszopiclone', true),
(530, 'Etelcalcetide', true),
(65, 'Ethacrynic acid derivatives', true),
(319, 'Ethambutol', true),
(845, 'Ethanolamine Antihistamines', true),
(376, 'Ethchlorvynol', true),
(377, 'Ethionamide', true),
(846, 'Ethylenediamine Antihistamines', true),
(378, 'Ethylenediamine Derivatives', true),
(379, 'Etomidate', true),
(990, 'Etranacogene Dezaparvovec', true),
(1033, 'Etrasimod', true),
(63, 'Eucalyptus', true),
(481, 'Factor Xa inhibitors', true),
(725, 'Fava Bean', true),
(1000, 'Fecal Microbiota', true),
(722, 'Fedratinib', true),
(724, 'Fenugreek', true),
(513, 'Ferulic acid', true),
(658, 'Fesoterodine', true),
(1093, 'Fexofenadine', true),
(177, 'Fibric acid derivatives', true),
(705, 'Fibroblast growth factor receptor (FGFR) tyrosine kinase inhibitor', true),
(1050, 'Fidanacogene Elaparvovec', true),
(264, 'Fidaxomicin', true),
(226, 'Fish Derivatives', true),
(1179, 'Fitusiran', true),
(1016, 'Flavocoxid', true),
(320, 'Flavoxate', true),
(913, 'Flax seed', true),
(227, 'Flecainide', true),
(380, 'Flucytosine', true),
(610, 'Fluoride', true),
(917, 'Fluorinated Propane Derivatives', true),
(824, 'Fluorine F-18 Radiopharmaceuticals', true),
(771, 'Fluoroestradiol F-18', true),
(182, 'Fluorouracil and related Pyrimidine Analogs', true),
(940, 'Fluticasone', true),
(253, 'Folic Acid', true),
(1094, 'Fondaparinux', true),
(808, 'Formoterol', true),
(244, 'Fosamprenavir', true),
(1097, 'Foscarnet', true),
(815, 'Fosdenopterin', true),
(611, 'Fostamatinib', true),
(773, 'Fostemsavir', true),
(501, 'Fructose and Derivatives', true),
(737, 'Fumaric acid esters', true),
(855, 'Fungus and Molds', true),

-- PDF 5: G-H allergens
(537, 'GABA analogs', true),
(699, 'GABA A Receptor Positive Modulators', true),
(272, 'Gadobenate dimeglumine', true),
(90, 'Gadolinium compounds', true),
(922, 'Gallium Derivatives', true),
(921, 'Gallium GA-68 Radiopharmaceuticals', true),
(827, 'Garlic', true),
(874, 'Gelatin and Derivatives', true),
(888, 'Gemcitabine', true),
(670, 'Geranium', true),
(667, 'Gilteritinib', true),
(474, 'Ginger and Related Compounds', true),
(1175, 'Givosiran', true),
(662, 'Glasdegib', true),
(1158, 'Glatiramer', true),
(381, 'Glucagon', true),
(274, 'Glucosamine', true),
(1177, 'Glucose', true),
(1075, 'Glutamic acid', true),
(901, 'Glutamine', true),
(831, 'Glycerol', true),
(1209, 'Glycine', true),
(461, 'Glycopeptides', true),
(1058, 'Glycopyrrolate', true),
(635, 'Glycopyrronium', true),
(1199, 'Glycosaminoglycans', true),
(217, 'Glycylcyclines', true),
(801, 'Goat (Caprine) Derivatives', true),
(1183, 'Goat Milk', true),
(49, 'Gold', true),
(178, 'Gonadotropin releasing factor', true),
(203, 'Gonadotropin-Releasing Hormone Analogs', true),
(1161, 'Gramicidin', true),
(865, 'Grapefruit', true),
(525, 'Grape', true),
(552, 'Green Dyes', true),
(249, 'Green Tea', true),
(58, 'Griseofulvin', true),
(382, 'Guaifenesin', true),
(321, 'Guanabenz', true),
(383, 'Guanethidine', true),
(322, 'Guanfacine', true),
(323, 'Guanidine', true),
(20, 'H2-blockers', true),
(295, 'Haemophilus B Conjugate vaccine', true),
(232, 'Halogenated Anesthetics', true),
(1159, 'Hamamelidaceae', true),
(102, 'Hamster (Cricetinae) Derivatives', true),
(1098, 'Hawthorn, Crataegus laevigata', true),
(488, 'HCV NS3/4A Protease Inhibitors', true),
(480, 'HCV NS5A inhibitors', true),
(745, 'Hemoglobin S polymerization inhibitor', true),
(213, 'Heparin', true),
(472, 'Hepatitis A', true),
(384, 'Hepatitis B', true),
(1013, 'Heptyl Glucoside', true),
(768, 'HER2 Tyrosine Kinase Inhibitors', true),
(229, 'Hetastarch', true),
(451, 'Hexachlorophene', true),
(686, 'Hexylresorcinol', true),
(1200, 'Hibiscus', true),
(214, 'Hirudins', true),
(721, 'Histamine-3 (H3) receptor antagonist/inverse agonists', true),
(926, 'Histamine', true),
(1165, 'Histidine', true),
(1045, 'Histone deacetylase (HDAC) inhibitors', true),
(54, 'HMG-CoA reductase inhibitors', true),
(1104, 'Horse Chestnut', true),
(41, 'Horse (Equine) Derivatives', true),
(532, 'House Dust Mite Allergen Extracts', true),
(749, 'Human Albumin Recombinant, Rice Derived', true),
(196, 'Human Immune Globulins', true),
(805, 'Human milk oligosaccharides (HMOs)', true),
(854, 'Human Plasma and Plasma-derived Coagulation Factors and Inhibitors', true),
(1207, 'Human Serum Albumin I-131', true),
(1018, 'Huperzia Derivatives', true),
(158, 'Hyaluronan derivatives', true),
(157, 'Hyaluronic acid', true),
(385, 'Hydantoins', true),
(324, 'Hydralazine', true),
(573, 'Hydroquinone', true),
(235, 'Hydroxyethyl Cellulose', true),
(387, 'Hydroxyurea', true),
(150, 'Hydroxyzine', true),
(678, 'Hyoscamine', true),
(712, 'Hypochlorite', true),
(1008, 'Hypoxia inducible factor (HIF) inhibitors', true),

-- PDF 6: I-L allergens
(832, 'Ibrexafungerp', true),
(269, 'Icodextrin', true),
(897, 'Icosapent', true),
(885, 'Ileal bile acid transporter (IBAT) inhibitors', true),
(1218, 'Imlunestrant', true),
(915, 'Inclisiran', true),
(476, 'Incretin Mimetics', true),
(993, 'Indium-111 Radiopharmaceuticals', true),
(169, 'Indoles', true),
(644, 'Influenza A Vaccines', true),
(286, 'Influenza B vaccines', true),
(197, 'Ingredients Derived from E. coli', true),
(75, 'Insulin (all)', true),
(1202, 'Insulin Isophane', true),
(1203, 'Insulin Regular', true),
(571, 'Integrase strand transfer inhibitors', true),
(124, 'Interferon Beta', true),
(109, 'Interferons (All)', true),
(208, 'Interleukins', true),
(994, 'Iobenguane', true),
(48, 'Iodine', true),
(992, 'Iodine Radiopharmaceuticals', true),
(236, 'Iodoquinol', true),
(605, 'Ionic Contrast Media', true),
(325, 'Ipratropium', true),
(47, 'Iron', true),
(995, 'Isocitrate Dehydrogenase 1 (IDH1) Inhibitors', true),
(1068, 'Isocitrate Dehydrogenase-1 (IDH1)/ Isocitrate Dehydrogenase-2 (IDH2) inhibitors', true),
(996, 'Isocitrate Dehydrogenase 2 (IDH2) Inhibitors', true),
(388, 'Isoniazid', true),
(1024, 'Isoxazoline Antiparasitic Agents', true),
(326, 'Isoxsuprine', true),
(1185, 'Ivy', true),
(619, 'Janus kinase (JAK) inhibitors', true),
(1053, 'Jellyfish Derivatives', true),
(883, 'Jojoba Derivatives', true),
(1014, 'Kava and Derivatives', true),
(327, 'Ketamine', true),
(194, 'Ketolides', true),
(1120, 'Ketotifen', true),
(507, 'Kiwi', true),
(825, 'KRAS G12C inhibitors', true),
(288, 'Krill oil', true),
(479, 'Lactobacillus', true),
(240, 'Lactose', true),
(930, 'Lagerstroemia Speciosa', true),
(570, 'Lamiaceae', true),
(664, 'Larotrectinib', true),
(731, 'Lasmiditan', true),
(68, 'Latex', true),
(1109, 'Lauraceae', true),
(1088, 'Laureth', true),
(515, 'Lauryl Laurate', true),
(991, 'L-Carnitine', true),
(540, 'Lecithin derivatives', true),
(1180, 'Legume', true),
(669, 'Lemongrass', true),
(1003, 'Lenacapavir', true),
(1181, 'Lentil', true),
(1056, 'Leucovorin', true),
(146, 'Leukotriene antagonists', true),
(823, 'Leuprolide', true),
(509, 'Levetiracetam analogs', true),
(85, 'Levodopa', true),
(1039, 'Levulinic Acid and Derivatives', true),
(953, 'Licorice (Glycyrrhiza)', true),
(672, 'Limonene', true),
(23, 'Lincosamides', true),
(389, 'Lindane', true),
(1105, 'Linolenic Acids', true),
(179, 'Lithium', true),

-- PDF 7: L-M allergens
(871, 'L-methylfolate', true),
(614, 'Lofexidine', true),
(122, 'Loop diuretics', true),
(578, 'Loratadine', true),
(890, 'Lorcaserin', true),
(212, 'Low Molecular Weight Heparins', true),
(328, 'Loxapine', true),
(1174, 'Lumasiran', true),
(755, 'Lumateperone', true),
(929, 'Lutetium LU-177 Radiopharmaceuticals', true),
(928, 'Lymphocyte activation gene-3 (LAG-3) blocking monoclonal antibodies', true),
(909, 'Lysine', true),
(636, 'Macimorelin', true),
(52, 'Macrolide Immunosuppressants', true),
(24, 'Macrolides', true),
(465, 'Magnesium', true),
(899, 'Maiibavir', true),
(738, 'Malic acid', true),
(270, 'Maltose', true),
(601, 'Manganese', true),
(390, 'Mannitol', true),
(884, 'Maralixibat', true),
(627, 'Marijuana', true),
(330, 'Mechlorethamine', true),
(941, 'Meclofenamic Acid', true),
(638, 'Mefloquine', true),
(684, 'Meglitinides', true),
(631, 'MEK inhibitors', true),
(729, 'Melanocortin-1 receptor (MC1-R) agonists', true),
(1163, 'Melatonin', true),
(1162, 'Melatonin Receptor Agonists', true),
(795, 'Melon', true),
(810, 'Melphalan', true),
(779, 'Memantine', true),
(285, 'Meningococcal Vaccines', true),
(222, 'Meningocococcal Polysaccharide Diptheria Toxoid Conjugate Vaccine', true),
(1079, 'Menin inhibitors', true),
(870, 'Menthol', true),
(392, 'Mepenzolate', true),
(234, 'Mequinol', true),
(186, 'Mercurial compounds', true),
(803, 'Mesenchymal-Epithelial Transition (MET) Inhibitors', true),
(393, 'Mesna', true),
(799, 'Messenger RNA of SARS-CoV-2 (COVID-19)', true),
(394, 'Mestranol', true),
(231, 'Metacresol', true),
(782, 'Metaxalone', true),
(396, 'Methenamine', true),
(397, 'Methimazole', true),
(167, 'Methotrexate compounds', true),
(332, 'Methyldopa', true),
(398, 'Methylene blue', true),
(817, 'Methylphenidate Derivatives', true),
(333, 'Metoclopramide', true),
(783, 'Metronidazole', true),
(399, 'Metyrapone', true),
(400, 'Metyrosine', true),
(256, 'Mifepristone', true),
(642, 'Migalastat', true),
(622, 'Milbemycins', true),
(914, 'Milk Thistle', true),
(292, 'Milnacipran', true),
(733, 'Minocycline', true),
(401, 'Minoxidil', true),
(569, 'Mint', true),
(923, 'Mitapivat', true),
(402, 'Mitomycin', true),
(403, 'Mitotane', true),
(334, 'Mitoxantrone', true),
(882, 'Mobocertinib', true),
(602, 'Modafinil', true),
(335, 'Molindone', true),
(498, 'Mollusc Derivatives', true),
(789, 'Molybdenum', true),
(963, 'Monkey (Simian) Derivatives', true),
(872, 'Monoalkylglycol Dialkyl Acid Esters', true),
(25, 'Monoamine oxidase inhibitors', true),
(26, 'Monobactams', true),
(1123, 'Monoclonal antibody-Deruxtecan Conjugates', true),
(1121, 'Moraceae', true),
(904, 'Moricizine', true),
(101, 'Mouse (Murine) Derivatives', true),
(336, 'Mupirocin', true),
(521, 'Mushrooms', true),
(1052, 'Myrtaceae Derivatives', true),
(1002, 'Nadofaragene Firadenovec', true),
(404, 'Naftifine', true),
(535, 'Naldemedine', true),
(473, 'Naloxone Derivatives', true),
(405, 'Natamycin', true),
(894, 'Nedocromil', true),
(1176, 'Nedosiran', true),
(242, 'Neomycin', true),
(706, 'Neratinib', true),

-- PDF 8: N-P allergens
(106, 'Neuraminidase inhibitors', true),
(1220, 'Neurokinin 1 (NK1) and neurokinin 3 (NK3) antagonists', true),
(1021, 'Neurokinin 3 receptor (NK3R) antagonists', true),
(155, 'Neuromuscular blockers', true),
(580, 'Niacinamide', true),
(487, 'Nickel', true),
(676, 'Nicotine', true),
(675, 'Nightshade (Solanacae)', true),
(536, 'Niraparib', true),
(1036, 'Nirogacestat', true),
(1168, 'Nitinol', true),
(139, 'Nitrates', true),
(164, 'Nitrofuran derivatives', true),
(104, 'Nitrogen mustards', true),
(784, 'Nitroimidazoles', true),
(719, 'Nitroimidazooxazines', true),
(105, 'Nitrosoureas', true),
(1061, 'Nitrous oxide', true),
(778, 'NMDA antagonists', true),
(130, 'Non-nucleoside reverse transcriptase inhibitors', true),
(861, 'Nonoxynol', true),
(95, 'Nonsteroidal antiandrogens', true),
(27, 'Nonsteroidal antiinflammatory drugs', true),
(866, 'Nonsteroidal mineralocorticoid receptor antagonists', true),
(714, 'Nuclear Export Inhibitor', true),
(129, 'Nucleoside reverse transcriptase inhibitors', true),
(734, 'Oat', true),
(862, 'Octoxynol', true),
(775, 'Octreotide', true),
(144, 'Oleic acid derivatives', true),
(1086, 'Olezarsen', true),
(908, 'Olive and Olive Derivatives', true),
(1011, 'Omaveloxolone', true),
(1029, 'Omega-6 Fatty Acids', true),
(1030, 'Omega-9 Fatty Acids', true),
(974, 'Omidenepag', true),
(829, 'Onion', true),
(558, 'Opiate Agonists-Antagonists', true),
(559, 'Opiate Antagonists', true),
(763, 'Oral CGRP Receptor Antagonists (GEPANTs)', true),
(806, 'Oral pyrimidine synthesis inhibitors', true),
(751, 'Orexin Receptor Antagonists', true),
(338, 'Orphenadrine', true),
(764, 'Osilodrostat', true),
(906, 'Oxazolidinedione Anticonvulsants', true),
(170, 'Oxazolidinones', true),
(780, 'Oxybates', true),
(339, 'Oxybutynin', true),
(386, 'Oxyquinoline', true),
(406, 'Oxytocin', true),
(766, 'Ozanimod', true),
(195, 'PABA derivatives', true),
(924, 'Pacritinib', true),
(911, 'Pafolacianine', true),
(674, 'Palmarosa Oil', true),
(820, 'Palm Kernel Acids', true),
(819, 'Palm oil derivatives', true),
(514, 'Palm Oil', true),
(1219, 'Paltusotine', true),
(942, 'Pamidronate', true),
(612, 'Panax ginseng', true),
(836, 'Pancrelipase', true),
(241, 'Papain', true),
(489, 'Papaya', true),
(463, 'Papillomavirus Protein antigens (Human)', true),
(582, 'Parabens', true),
(1054, 'Paraffin and Derivatives', true),
(1069, 'Parathyroid hormone-related protein (PTHrP) analogs', true),
(502, 'Paritaprevir', true),
(340, 'Paroxetine', true),
(527, 'PARP Inhibitors', true),
(641, 'Patisiran', true),
(646, 'PD-1 inhibitor', true),
(647, 'PD-L1 inhibitor', true),
(626, 'Peach', true),
(38, 'Peanut Family', true),
(486, 'Peas', true),
(1062, 'PEG and Dimethicone Copolymers', true),
(821, 'Pegcetacoplan', true),
(1048, 'Pegulicianine', true),
(967, 'Pemetrexed', true),
(407, 'Pemoline', true),
(81, 'Penicillamine', true),
(341, 'Penicillin G', true),
(135, 'Penicillin G procaine', true),
(1, 'Penicillins', true),
(730, 'Penicillin V', true),
(342, 'Pentamidine', true),
(343, 'Pergolide', true),
(1191, 'Persulfates', true),
(475, 'Pertussis', true),
(1114, 'Petrolatum', true),
(718, 'Pexidartinib', true),
(184, 'Phenanthrene opioids', true),
(344, 'Phenazopyridine', true),
(688, 'Phenol', true),
(44, 'Phenothiazines', true),
(346, 'Phenoxybenzamine', true),
(347, 'Phentolamine', true),
(1211, 'Phenylalanine hydroxylase (PAH) activators', true),

-- PDF 9: P-end allergens
(408, 'Phenylalanine', true),
(409, 'Phenylbutazone', true),
(976, 'Phenylbutyrate', true),
(837, 'Phenylpiperazine Antidepressants', true),
(183, 'Phenylpiperidine opioids', true),
(562, 'Phenylpropylamines', true),
(903, 'Phenyltoloxamine', true),
(561, 'Phosphatidylinositol-3-kinase (PI3K) Inhibitors', true),
(717, 'Phosphocholine', true),
(1060, 'Phosphodiesterase 3 and 4 (PDE3 and PDE4) inhibitors', true),
(127, 'Phosphodiesterase 5 (PDE5) inhibitors', true),
(651, 'Phosphonates', true),
(1009, 'Phosphorus', true),
(348, 'Pilocarpine', true),
(512, 'Pimavanserin', true),
(410, 'Pimozide', true),
(863, 'Pineapple Derivatives', true),
(859, 'Pine Derivatives', true),
(1084, 'Pine nut', true),
(1073, 'Piperaceae', true),
(834, 'Piperazine Antihistamines', true),
(618, 'Pitavastatin', true),
(720, 'Pitolisant', true),
(1049, 'Pivmecillinam', true),
(1034, 'Plantaginaceae Derivatives', true),
(520, 'Plant-based Enzymes', true),
(1152, 'Platelet Glycoprotein IIb/IIIa Inhibitors', true),
(53, 'Platinum compounds', true),
(723, 'Pleuromutilin Derivatives', true),
(1222, 'Plozasiran', true),
(482, 'Pneumococcal Vaccine', true),
(411, 'Poliovirus vaccine', true),
(299, 'Pollen Extracts', true),
(962, 'Poloxamer', true),
(1111, 'Polycarbophil', true),
(798, 'Polyethylene Glycol', true),
(853, 'Polymeric Biguanides', true),
(912, 'Polymyxin B', true),
(584, 'Polysorbates', true),
(1189, 'Poppy', true),
(42, 'Pork and Pig (Porcine) Derivatives', true),
(187, 'Porphyrins', true),
(949, 'Potassium-competitive acid blockers', true),
(585, 'Potassium', true),
(74, 'Potassium-sparing diuretics', true),
(661, 'Potato', true),
(873, 'Povidone and Derivatives', true),
(1192, 'Prademagene Zamikeracel', true),
(350, 'Praziquantel', true),
(237, 'Primaquine', true),
(280, 'Probenecid', true),
(136, 'Procainamide', true),
(788, 'Procaine', true),
(215, 'Progestins', true),
(848, 'Propofol Derivatives', true),
(977, 'Propylene glycol', true),
(413, 'Propylthiouracil', true),
(147, 'Prostaglandins', true),
(166, 'Protamine compounds', true),
(55, 'Protease inhibitors', true),
(284, 'Protein C Concentrate (Human)', true),
(33, 'Proton pump inhibitors', true),
(682, 'Prucalopride', true),
(414, 'Psyllium', true),
(656, 'Pumpkin', true),
(181, 'Purine analogs', true),
(1099, 'Purple/Violet Dyes', true),
(528, 'Pyrantel', true),
(415, 'Pyrazinamide', true),
(838, 'Pyrazoles', true),
(199, 'Pyrethrin Derivatives', true),
(416, 'Pyrimethamine', true),
(1221, 'Pyrimidine nucleosides', true),
(687, 'Pyrogallol', true),
(965, 'Quassia vinegar M.S.', true),
(165, 'Quaternary ammonium compounds', true),
(937, 'Quercetin', true),
(300, 'Quetiapine', true),
(1077, 'Quillaja saponaria', true),
(141, 'Quinazoline Compounds', true),
(97, 'Quinolones', true),
(1023, 'Quizartinib', true),
(466, 'Rabbit (Leporine) Derivatives', true),
(655, 'Rabies', true),
(200, 'Ragweed Sensitivity', true),
(255, 'Rapamycin Derivatives', true),
(898, 'Rat (Murine)', true),
(46, 'Rauwolfia Alkaloids', true),
(648, 'Recombinant Adenosine Deaminase', true),
(551, 'Red Dyes', true),
(620, 'Red Meat', true),
(893, 'Remdesivir', true),
(777, 'Remimazolam', true),
(685, 'Resorcinol', true),
(586, 'Retinoids', true),
(728, 'Retinoids (topical)', true),
(1092, 'Rhamnaceae', true)

ON CONFLICT (vios_code) DO UPDATE SET
  name = EXCLUDED.name,
  is_active = true,
  updated_at = now();