name: Deploy Vitaluxe Staging

on:
  push:
    branches:
      - develop  # Auto-deploy staging when develop updates
  workflow_dispatch:  # Allow manual trigger

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

 env:
  AWS_REGION: us-west-2
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_STAGING }}
  LIGHTSAIL_SERVICE_NAME: ${{ secrets.LIGHTSAIL_SERVICE_NAME_STAGING }}
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  VITE_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker Image for Staging
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: vitaluxe-staging:latest
          build-args: |
            VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
            VITE_SUPABASE_PUBLISHABLE_KEY=${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY }}

      - name: Login & Push to Staging ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 382806778137.dkr.ecr.us-west-2.amazonaws.com
          docker tag vitaluxe-staging:latest $ECR_REPOSITORY:latest
          docker push $ECR_REPOSITORY:latest

      - name: Deploy Staging to Lightsail
        run: |
          aws lightsail create-container-service-deployment \
            --service-name "$LIGHTSAIL_SERVICE_NAME" \
            --containers "{
              \"vitaluxe-staging\": {
                \"image\": \"${ECR_REPOSITORY}:latest\",
                \"ports\": {\"8080\": \"HTTP\"}
              }
            }" \
            --public-endpoint "{
              \"containerName\": \"vitaluxe-staging\",
              \"containerPort\": 8080
            }"

      - name: Display Lightsail URL
        run: |
          echo "Fetching staging service URL..."
          URL=$(aws lightsail get-container-services \
            --service-name "$LIGHTSAIL_SERVICE_NAME" \
            --query "containerServices[0].url" \
            --output text)
          echo "🌍 Staging URL: $URL"
